import Head from 'next/head'


export default function Pricing() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pricing</h1>
      
    </div>
  )
}
